# Generated by Django 2.0.5 on 2018-05-31 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.SlugField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SlugField(help_text='no spaces or punctuation except hyphen', max_length=200, primary_key=True, serialize=False, verbose_name='label')),
                ('name', models.CharField(max_length=200)),
                ('short_description_en', models.TextField(verbose_name='Short description (English)')),
                ('short_description_fr', models.TextField(verbose_name='Short description (French)')),
                ('long_description_en', models.TextField(blank=True, verbose_name='Long description (English)')),
                ('long_description_fr', models.TextField(blank=True, verbose_name='Long description (French)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('licence', models.CharField(blank=True, max_length=50)),
                ('documentation', models.URLField(blank=True, help_text='URL of the project documentation')),
                ('download', models.URLField(blank=True, help_text='For software projects, URL where the software can be downloaded')),
                ('source_code', models.URLField(blank=True, help_text='For open-source software projects, URL where the source code is available')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.SlugField(help_text='Please do not change', primary_key=True, serialize=False, verbose_name='label')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('middle_initials', models.CharField(blank=True, max_length=10, verbose_name='Middle initials')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='E-mail')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Title')),
                ('is_team_leader', models.BooleanField(default=False, verbose_name='Group leader')),
                ('interests_en', models.TextField(blank=True, verbose_name='Research interests (English)')),
                ('interests_fr', models.TextField(blank=True, verbose_name='Research interests (French)')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.PositionType')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='directory.Researcher')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.SlugField(help_text='Please do not change', max_length=200, primary_key=True, serialize=False, verbose_name='label')),
                ('name_en', models.CharField(max_length=200, verbose_name='English name')),
                ('name_fr', models.CharField(max_length=200, verbose_name='French name')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (French)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.Laboratory', verbose_name='laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('title_en', models.CharField(max_length=100)),
                ('title_fr', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('content_en', models.TextField()),
                ('content_fr', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'text',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.ResourceType'),
        ),
        migrations.AddField(
            model_name='researcher',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='directory.Team', verbose_name='research group'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='directory.Researcher', verbose_name='contributors'),
        ),
    ]
