# Generated by Django 2.0.5 on 2018-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='orcid',
            field=models.CharField(blank=True, max_length=19, verbose_name='ORCID'),
        ),
    ]
